# Generated by Django 3.2.5 on 2021-08-18 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookDriveApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donator_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('Numberofbooks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('KindofBooks', models.CharField(choices=[('Novel', 'Novel'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('History', 'History'), ('Textbook', 'Textbook'), ('Encyclopedia', 'Encyclopedia'), ('Childrens', 'Childrens'), ('Fantasy', 'Fantasy'), ('Poetry', 'Poetry'), ('Spiritual', 'Spiritual'), ('Science', 'Science'), ('Sports ', 'Sports '), ('Travel ', 'Travel '), ('Literatute ', 'Literature '), ('Other', 'Other')], max_length=300)),
                ('Status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user_info',
            name='numberofbooks',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
