# Generated by Django 3.2.5 on 2021-08-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookDriveApp', '0002_auto_20210818_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
