# Generated by Django 3.2.5 on 2021-08-18 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookDriveApp', '0003_delete_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('kindofbooks', models.CharField(max_length=150)),
                ('numberofbooks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(max_length=150)),
                ('user_categories', models.CharField(choices=[('Donator', 'Donator'), ('Benificiary', 'Benificiary')], max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='donator_info',
        ),
    ]
