# Generated by Django 3.2.5 on 2021-08-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookDriveApp', '0005_auto_20210818_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Pick-up', 'Pick-up')], default='Pending', max_length=200),
        ),
    ]
