# Generated by Django 3.2.5 on 2021-08-23 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookDriveApp', '0007_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='benif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('kindofbooks', models.CharField(choices=[('Novel', 'Novel'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('History', 'History'), ('Textbook', 'Textbook'), ('Encyclopedia', 'Encyclopedia'), ('Childrens', 'Childrens'), ('Fantasy', 'Fantasy'), ('Poetry', 'Poetry'), ('Spiritual', 'Spiritual'), ('Science', 'Science'), ('Math', 'Math'), ('Textbook', 'Textbook'), ('Journal', 'Journal'), ('Self Help', 'Self Help'), ('others', 'others')], max_length=150)),
                ('numberofbooks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Pick-up', 'Pick-up')], default='Pending', max_length=200)),
            ],
        ),
    ]
