# Generated by Django 3.2.5 on 2021-08-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookDriveApp', '0008_benif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
